main: l3.c
	gcc l3.c -o lista3
$(info )
$(info  Usage:) 
$(info  compression:   	./lista3 -c -plain/-delta/-omega/-fibonacci/-gamma <input file> <output file>)
$(info decompression: 	./lista3 -d -plain/-delta/-omega/-fibonacci/-gamma <input file> <output file>)
$(info )
