main: main.c
	gcc -std=c11 -o main main.c -lm

$(info )
$(info  usage: PLIK main:)
$(info )
$(info  usage:   ./main <compress/decompress> <input_file> <output_file> <bits>)  
$(info )
$(info <bits> - tylko w przypadku compress)
$(info )



